version: '3'

services:
  php:
    image: dev
    build:
      context: ./php
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    working_dir: /app
    volumes:
      - ${APP_PATH}:/app:rw
      - ./logs/php:/app/var/log:rw
    depends_on:
      - mysql
    environment:
      TZ: ${TZ:-UTC}
      DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-app}@mysql:3306/${MYSQL_DATABASE:-app}
      PHP_IDE_CONFIG: serverName=${IDE_SERVER_NAME:-docker}

  nginx:
    build: ./nginx
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs/nginx:/var/log/nginx:rw
      - ${APP_PATH}/public:/app/public:ro
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./data/db/${MYSQL_DATABASE:-app}:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
