version: '3.4'

services:
  php:
    build:
      context: ${APP_PATH}
      target: test
      dockerfile: ./php/Dockerfile
    volumes:
      - $SSH_AUTH_SOCK:/ssh-auth.sock:ro
    depends_on:
      - mysql
    environment:
      TZ: ${TZ:-UTC}
      DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-app}@mysql:3306/${MYSQL_DATABASE:-app}
      SSH_AUTH_SOCK: /ssh-auth.sock
      APP_ENV: test

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
    tmpfs:
      - /var/lib/mysql
